### ISSUE TITLE
Markdown support?

### ISSUE THREAD

**Issue by sholsapp** [sixninetynine/not#1]
This project is unreasonably awesome.

I write tons of my tons in markdown and I'm wondering if you're open for adding (or accepting a PR) for something like that. I'm thinking more along the lines of adding a file extension to the temp file so I get syntax highlighting, not along the lines of compiling to/from HTML so the Evernote interface displays it correctly (although, that would be awesome, it sounds hard).

Thoughts?

**Comment by lorencarvalho** [comment]
I'm definitely into the idea of using markdown -- It's my markup language of choice as well

when I first put `not` together I anticipated only using plaintext because my purpose was to avoid going into evernote at all (where the markdown would render), but syntax highlighting is an interesting proposal that puts a new spin on things... 

an somewhat non-obtrusive option would be to prepend each new note with a modeline hint (if you are using VIM):
`<!-- vim: set filetype=markdown : -->`

though I've been mucking with it for like 10 minutes now and can't get it to highlight properly (i might just be missing a vim plugin).

I think I'd ultimately like to just use markdown as the default markup for all the notes made/edited in `not`, especially because the weird XML stuff that evernote does is already annoying and I don't really even handle it that well (see the `NotClient.save()` method)

**Comment by sholsapp** [comment]
If you're using a plugin like plasticboy/vim-markdown, it would be sufficient to just name the temporarily file with a `.md` extension. That would work for just markdown, obviously. Coming up with a more extensible way to support other peoples' markup language of choice is harder.

**Comment by lorencarvalho** [comment]
https://github.com/sixninetynine/not/commit/1af414c9a446978003a7d159bbaccf2c0afc073d
