### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by sholsapp** [sixninetynine/not#2]
Tagging would be nice so that it's easy to separate out work life from grocery life from project life, right? Or is this going down the path of too complicated and not _dumb as rocks simple_?

**Comment by lorencarvalho** [comment]
yes!!!

I use tags in evernote _heavily_ and when I first thought of this thing I wanted to basically just put some trigger-type syntax at the bottom of any note, like:

```
this is some note
this is more of the note

tags: grocery,personal,fun
```

they could then be parsed & stripped out during save() so that they don't end up in the saved text of the note, then added back into the body of the note if you edit it again. Potentially making this thing smarter than it should be, but I think if it's human readable-ish and straightforward it doesn't mess with the philosophy :)

what do you think?

**Comment by sholsapp** [comment]
Yeah, that'd be perfect and hides it from the UI, which is super simple. I'll brush up on my evernote api.

**Comment by lorencarvalho** [comment]
here's something for starters

4a42fc9b0d09812a91cad95ea6e3be4db3a43714

**Comment by lorencarvalho** [comment]
good enuf https://github.com/sixninetynine/not/commit/a0a5976b3a6cd97ca55ad2ef7eddfe2df82ec0f1
